plugins:
  - rubocop-minitest
  - rubocop-rails

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.2
  Exclude:
    - "test/tmp/**/*"
    - "vendor/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 140

Metrics/AbcSize:
  Max: 50

Metrics/BlockLength:
  Exclude:
    - "mempalace-rb.gemspec"
    - "test/**/*"
    - "lib/generators/mempalace/migrations/templates/create_mempalace_tables.rb.tt"

Metrics/ClassLength:
  Max: 180

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/MethodLength:
  Max: 40

Metrics/ParameterLists:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

Gemspec/DevelopmentDependencies:
  Enabled: false

Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false

Minitest/MultipleAssertions:
  Enabled: false

Minitest/SkipEnsure:
  Enabled: false

Rails/ApplicationJob:
  Enabled: false

Rails/ApplicationRecord:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/RefuteMethods:
  Enabled: false

Style/ArgumentsForwarding:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/Documentation:
  Enabled: false
